# Generated by Django 5.2.8 on 2025-11-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('place', models.CharField(max_length=200)),
                ('capacite', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('CULTURAL', 'Cultural & Historical'), ('MUSIC', 'Music & Arts'), ('SEASONAL', 'Seasonal & Agricultural'), ('SPORT', 'Sporting Events'), ('CRAFT', 'Craftsmanship & Shopping')], max_length=20)),
                ('score_avg', models.FloatField(default=0.0)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
