# Generated by Django 5.2.8 on 2025-11-13 21:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Le titre ne doit contenir que des lettres, chiffres, espaces ou tirets.', regex='^[a-zA-ZÀ-ÿ0-9\\s\\-\\_\\\'"]+$')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'La description doit contenir au moins 20 caractères.')])),
                ('type_media', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10)),
                ('chemin_media', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi'], message='Le fichier doit être une image (.jpg, .png) ou une vidéo (.mp4, .mov, .avi).')])),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nb_likes', models.PositiveIntegerField(default=0)),
                ('nb_dislikes', models.PositiveIntegerField(default=0)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
                ('nb_infractions', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(default='en_attente', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
