# Generated by Django 5.2.6 on 2025-11-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='chemin_media',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
