# Generated by Django 5.2.6 on 2025-11-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_article_disliked_by_article_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
