# Generated by Django 5.2.6 on 2025-11-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_article_latitude_article_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='article',
            name='longitude',
        ),
    ]
