# Generated by Django 5.2.6 on 2025-11-09 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_article_dislikes_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.AlterField(
            model_name='article',
            name='chemin_media',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi'], message='Le fichier doit être une image (.jpg, .png) ou une vidéo (.mp4, .mov, .avi).')]),
        ),
    ]
