# Generated by Django 5.2.8 on 2025-11-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('cash', 'Espèces'), ('transfer', 'Virement'), ('online', 'Paiement en ligne')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
