# Generated by Django 5.2.8 on 2025-11-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('Card', 'Carte bancaire'), ('Cash', 'Espèces'), ('Cheque', 'Chèque')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
