# Generated by Django 5.2.8 on 2025-11-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
