# Generated by Django 5.2.8 on 2025-11-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipationApp', '0002_participation_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='id',
        ),
        migrations.AddField(
            model_name='participation',
            name='id_participation',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
