# Generated by Django 5.2.8 on 2025-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipationApp', '0003_remove_participation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
