# Generated by Django 5.2.8 on 2025-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParticipationApp', '0004_participation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
