# Generated by Django 5.2.8 on 2025-11-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_risk_level',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_security_score',
            field=models.IntegerField(default=0, help_text='Score IA 0-100'),
        ),
    ]
