# Generated by Django 5.2.6 on 2025-11-20 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_rename_bad_post_attempts_userprofile_infractions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='infractions',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bad_post_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
