# Generated by Django 5.2.6 on 2025-11-09 13:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Le titre ne doit contenir que des lettres, chiffres et espaces.', regex='^[\\w\\s]+$')])),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('maison_dhote', 'Maison d’hôte'), ('gite_rural', 'Gîte rural'), ('camping_tente', 'Camping / Tente'), ('hotel', 'Hôtel'), ('riad', 'Riad / Dar'), ('autre', 'Autre')], max_length=50)),
                ('gouvernorat', models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('kef', 'Le Kef'), ('siliana', 'Siliana'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('sidi_bouzid', 'Sidi Bouzid'), ('gabes', 'Gabès'), ('medenine', 'Medenine'), ('tataouine', 'Tataouine'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili'), ('gafsa', 'Gafsa')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('utilisateurs', models.ManyToManyField(related_name='accommodations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodations/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='AccomodationApp.accommodation')),
            ],
        ),
    ]
