# Generated by Django 5.2.6 on 2025-11-09 14:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccomodationApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='est_actif',
            field=models.BooleanField(default=True, help_text='Le logement est-il actuellement disponible à la location ?'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Prix de base (peut être surchargé par les chambres)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.CharField(choices=[('maison_dhote', "Maison d'hôte"), ('gite_rural', 'Gîte rural'), ('camping_tente', 'Camping / Tente'), ('hotel', 'Hôtel'), ('riad', 'Riad / Dar'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Numéro ou nom de la chambre', max_length=50)),
                ('type_chambre', models.CharField(choices=[('simple', 'Chambre Simple'), ('double', 'Chambre Double'), ('twin', 'Chambre Twin'), ('triple', 'Chambre Triple'), ('suite', 'Suite'), ('familiale', 'Chambre Familiale'), ('dortoir', 'Dortoir')], max_length=20)),
                ('nombre_lits', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('capacite', models.PositiveIntegerField(help_text='Nombre de personnes maximum', validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_nuit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('est_disponible', models.BooleanField(default=True, help_text='La chambre est-elle actuellement disponible ?')),
                ('date_ajoutee', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='AccomodationApp.accommodation')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'unique_together': {('accommodation', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_personnes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles pour la réservation', null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='AccomodationApp.chambre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
