# Generated by Django 5.2.6 on 2025-11-09 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccomodationApp', '0002_accommodation_adresse_accommodation_est_actif_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ['-date_ajoutee'], 'verbose_name': 'Hébergement', 'verbose_name_plural': 'Hébergements'},
        ),
        migrations.AlterModelOptions(
            name='chambre',
            options={'ordering': ['accommodation', 'numero'], 'verbose_name': 'Chambre', 'verbose_name_plural': 'Chambres'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterField(
            model_name='chambre',
            name='nombre_lits',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de lits dans la chambre', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix_nuit',
            field=models.DecimalField(decimal_places=2, help_text='Prix par nuit pour cette chambre', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_personnes',
            field=models.PositiveIntegerField(help_text='Nombre de personnes pour cette réservation', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, help_text='Prix total de la réservation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
