# Generated by Django 5.2.8 on 2025-11-14 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccomodationApp', '0003_alter_accommodation_options_alter_chambre_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='capacite',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='est_disponible',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='prix',
            field=models.DecimalField(decimal_places=2, help_text='Prix minimum peut être surchargé par les chambres', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
