# Generated by Django 5.2.6 on 2025-11-22 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccomodationApp', '0005_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text='Date de début de la réservation')),
                ('date_fin', models.DateField(help_text='Date de fin de la réservation')),
                ('nombre_personnes', models.PositiveIntegerField(help_text='Nombre de personnes pour cette réservation', validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_total', models.DecimalField(decimal_places=2, help_text='Prix total de la réservation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles pour la réservation', null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='AccomodationApp.chambre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
